[package]
name = "leptos-locatorjs"
version = "0.2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
proc-macro2 = { version = "1.0.85", features = ["span-locations"] }
quote = "1.0.36"
regex = "1.10.4"
syn = {version = "2.0.66", features = ["full"]}
[lib]
proc-macro = true
path = "lib.rs"
